#
title: USM COS 470 The Art and Craft of Software Development (Spring 2021)
theme: minima
excerpt_separator: <!--more-->
github_username: usm-cos470-s21
twitter_username: stephenhouser
author: Stephen Houser
email: houser@maine.edu
description: University of Southern Maine, Computer Science
timezone: America/New York

collections:
  notes:
    output: true
    sort_by: order
  assignments:
    output: true
    sort_by: order
  # samples:
  #   output: true
  #   sort_by: order

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
      hidden: false
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      hidden: false
  # - scope:
  #     path: ""
  #     type: "samples"
  #   values:
  #     layout: "sample"
  #     hidden: false
      
exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "TODO.md"]
